apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kitchensink
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: kitchensink-blue-loadbalancer
    weight: 100
  alternateBackends:
    - kind: Service
      name: kitchensink-green-loadbalancer
      weight: 0
